### PR TITLE
Fix GPG Keys line, so CentOS 7.x yum update works on c1 servers

### LINKED ISSUE #22: C1 ARM, CentOS 7 problem with yum updates
I have recently created a baremetal ARM C1 server running CentOS 7. One of the first commands I ran was

yum update -y

At the bottom of the output was the following error, preventing the update from going ahead:

```
Total size: 101 M
Downloading packages:
warning: /var/cache/yum/armhfp/7/updates/packages/tzdata-2017b-1.el7.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID f 4a80eb5: NOKEY
Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-AltArch-Arm32


The GPG keys listed for the "CentOS-7 - Updates" repository are already installed but they are not correct for this packa ge.
Check that the correct key URLs are configured for this repository.


Failing package is: tzdata-2017b-1.el7.noarch
GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-AltArch-Arm32
```

This seems to be related to the image you use to deploy to the baremetal server. Please, can someone indicate how I can resolve this?

This is what I see in the repo files...

```
[root@scw-xxxxx ~]# cat /etc/yum.repos.d//CentOS-Base.repo
[base]
name=CentOS-$releasever - Base
mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=os
baseurl=http://mirror.centos.org/altarch/$releasever/os/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-AltArch-Arm32

#released updates
[updates]
name=CentOS-$releasever - Updates
mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=updates
baseurl=http://mirror.centos.org/altarch/$releasever/updates/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-AltArch-Arm32

#additional packages that may be useful
[extras]
name=CentOS-$releasever - Extras
mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=extras
baseurl=http://mirror.centos.org/altarch/$releasever/extras/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-AltArch-Arm32
```

The CentOS build that comes with the server seems to have the line gpgkey= listed twice. is this an error? Something seems wrong with the above. I've been asked by Scaleway support to post my issue here.

Can anyone help or comment on why the yum updates won't run based on the repo output above please?

Regards
Rob

### PR DESCRIPTION
**Pull request by justinclift**
This fixes #22.  Tested on a newly created c1 server in Paris just now.

### CODE REVIEW

**Comment by sieben** [comment]
@justinclift Could you rebase?

**Comment by justinclift** [comment]
Yep, can do.  Gimme a few minutes. :smile:

**Comment by sieben** [comment]
Thank you very much for your fix :)

Le jeu. 31 mai 2018 à 11:16, Justin Clift <notifications@github.com> a
écrit :

**Comment by justinclift** [comment]
You're welcome. :smile:

**Pull request merged**
